name: flyingpigeon
channels:
- defaults
- birdhouse
# cartopy nco cdo ... etc
#- ioos
- conda-forge
# ocgis
- nesii
# the r hell ...
- r
- bioconda  # r-mclust
dependencies:
- python=2.7.12
# - gcc=4.8.5
# - pyopenssl=0.16.0
# - cryptography=1.4
# - icu=54.1
# - libiconv=1.14
# tests
- pytest
# docs
- sphinx
- sphinx_rtd_theme
# ipython
- ipython=4.2.0
# wps
- nginx=1.10.1
- supervisor=3.1.3
- gunicorn=19.1.0
- gevent
- pywps=3.2.6
- mako
# misc
- pywget
- pyyaml
# cdo
- cdo=1.7.0
- pycdo
- jpeg=8d
# numeric
- pandas#=0.18.1
- statsmodels#=0.6.1
- scikit-learn#=0.17.1
# cartopy
- cartopy=0.14.2 # conflicts with numpy >1.10
- iris=1.9.2 # conflicts with numpy >1.10
# ocgis ... drives me nuts :(
- ocgis-next=1.4.0.dev1=py27_2
- esmpy=7.0.0=py27_3
- esmf=7.0.0=2 
# - icclim=4.1.1
# - netcdf4=1.2.2
# - libnetcdf=4.3.3.1=3
# - gdal=1.11.3=py27_0
# - numpy=1.11.1=py27_0
# - proj.4=4.9.2
# - udunits2=2.2.20
# - geos=3.4.2
# - cf_units=1.1
# - curl=7.45
# - fiona=1.6.3=py27_0
# - libspatialindex=1.8.5
# - munch=2.0.4
# - rtree=0.8.2
# analogue
- castf90=0.1.2
- netcdf-fortran=4.4.3
- nco=4.5.5
# r
# - r=3.2.2 
# - rpy2=2.7.0
# - r-mclust=5.1
# - r-ncdf4=1.13
# - r-fields=8.4
# - r-gridextra=2.0.0
# - r-cairo=1.5_9
# - pip:
#   - genshi==0.7
#   - pygbif==0.1.4
#   - cdo==1.3.0
#   - sphinx-autoapi==0.4.0